require('core.plugin_config.colors')
require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.telescope')
require('core.plugin_config.treesitter')
require('core.plugin_config.vim-autopairs')
require('core.plugin_config.lspconfig')
require('core.plugin_config.dressing')
